#!/usr/bin/env python3
import sys
import os
import re
import json
from datetime import datetime, timedelta
import pandas as pd

try:
    import yfinance as yf
except ImportError:
    print("Error: yfinance is required. Install with: pip install yfinance")
    sys.exit(1)

# Fix for Windows terminal encoding issues
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def parse_trade_markdown(file_path):
    """
    Parses a TRADE-*.md file to extract trade parameters.
    Returns a dict with ticker, entries, stops, targets, and date.
    """
    if not os.path.exists(file_path):
        return None

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    data = {
        "ticker": None,
        "date": None,
        "entry_low": None,
        "entry_high": None,
        "stop_loss": None,
        "target": None,
        "direction": "long", # default
    }

    # Extract Ticker (e.g., # Trade Analysis: DE40)
    ticker_match = re.search(r"# Trade Analysis:\s*([A-Z0-9]+)", content)
    if ticker_match:
        data["ticker"] = ticker_match.group(1)
        # Handle DAX alias
        if data["ticker"] == "DE40":
            data["ticker_symbol"] = "^GDAXI"
        else:
            data["ticker_symbol"] = data["ticker"]

    # Extract Date (e.g., April 16, 2026)
    date_match = re.search(r"Generated by AI Trading Analyst \| (.*?)$", content, re.MULTILINE)
    if date_match:
        try:
            data["date"] = datetime.strptime(date_match.group(1).strip(), "%B %d, %Y")
        except:
            pass

    # Extract Entry/Exit Strategy table values
    # | Entry Zone | 23,800 - 24,100 | ... |
    # | Stop Loss  | 24,350 | ... |
    # | Target 1   | 25,500 | ... |
    
    def clean_num(s):
        return float(s.replace(",", "").replace("$", "").replace("–", "-").split()[0])

    entry_match = re.search(r"Entry Zone\s*\|\s*([\d,]+)\s*[-–]\s*([\d,]+)", content)
    if entry_match:
        data["entry_low"] = clean_num(entry_match.group(1))
        data["entry_high"] = clean_num(entry_match.group(2))

    stop_match = re.search(r"Stop Loss\s*\|\s*([\d,]+)", content)
    if stop_match:
        data["stop_loss"] = clean_num(stop_match.group(1))

    target_match = re.search(r"Target 1\s*\|\s*([\d,]+)", content)
    if target_match:
        data["target"] = clean_num(target_match.group(1))

    # Determine Direction based on Target vs Entry
    if data["target"] and data["entry_low"] and data["target"] < data["entry_low"]:
        data["direction"] = "short"
    else:
        data["direction"] = "long"

    return data

def verify_consistency(data):
    """Checks for logical errors in the trade setup."""
    issues = []
    
    if data["direction"] == "long":
        if data["stop_loss"] and data["entry_high"] and data["stop_loss"] > data["entry_high"]:
            issues.append(f"LOGIC ERROR: Long trade has Stop Loss ({data['stop_loss']}) ABOVE Entry Zone ({data['entry_high']}).")
        if data["target"] and data["entry_high"] and data["target"] < data["entry_high"]:
            issues.append(f"LOGIC ERROR: Long trade has Target ({data['target']}) BELOW Entry Zone.")
    else: # short
        if data["stop_loss"] and data["entry_low"] and data["stop_loss"] < data["entry_low"]:
            issues.append(f"LOGIC ERROR: Short trade has Stop Loss BELOW Entry Zone.")
        if data["target"] and data["entry_low"] and data["target"] > data["entry_low"]:
            issues.append(f"LOGIC ERROR: Short trade has Target ABOVE Entry Zone.")
            
    return issues

def backtest_setup(data):
    """Fetches data and checks if the trade parameters align with history."""
    if not data["ticker_symbol"] or not data["date"]:
        return "Error: Ticker or Date missing."

    # Fetch history around the report date
    start_date = (data["date"] - timedelta(days=10)).strftime("%Y-%m-%d")
    end_date = (data["date"] + timedelta(days=1)).strftime("%Y-%m-%d")
    
    try:
        ticker = yf.Ticker(data["ticker_symbol"])
        df = ticker.history(start=start_date, end=end_date)
    except Exception as e:
        return f"Error fetching data: {e}"

    if df.empty:
        return f"No data found for {data['ticker_symbol']} in range {start_date} to {end_date}"

    results = []
    results.append(f"--- Verification Report for {data['ticker']} ({data['date'].date()}) ---")
    
    # Check current price claim
    last_price = df.iloc[-1]["Close"]
    results.append(f"Verified Last Price: {last_price:.2f}")
    
    # Check if Entry Zone was reached in last 5 sessions
    recent = df.tail(5)
    entry_hit = recent[(recent["Low"] <= data["entry_high"]) & (recent["High"] >= data["entry_low"])]
    
    if not entry_hit.empty:
        results.append(f"✅ Entry Triggered: Price entered {data['entry_low']}-{data['entry_high']} on {entry_hit.index[0].date()}")
    else:
        results.append(f"⚠️ Entry Not Triggered: Price hasn't touched the zone {data['entry_low']}-{data['entry_high']} in recent sessions.")

    # Consistency Check
    issues = verify_consistency(data)
    if issues:
        for issue in issues:
            results.append(f"❌ {issue}")
    else:
        results.append("✅ Logical Consistency: Passed.")

    return "\n".join(results)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python backtest_analysis.py <path_to_trade_md>")
        sys.exit(1)

    file_path = sys.argv[1]
    trade_data = parse_trade_markdown(file_path)
    if not trade_data:
        print(f"Failed to parse {file_path}")
        sys.exit(1)

    report = backtest_setup(trade_data)
    print(report)
